spring:
  datasource:
    url: jdbc:mysql://localhost:3306/internship2?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  servlet:
    context-path: /messageboard
  tomcat:
    uri-encoding: UTF-8
