spring:
  datasource:
    url: jdbc:mysql://localhost:3306/internship?serverTimezone=UTC
    username: root
    password: czx6296456852
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  servlet:
    context-path: /messageboard

