//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : NoPay.java
//  @ Date : 2019/9/5
//  @ Author : 
//
//


/**
 * 未支付状态
 */
public class NoPay implements BillState {


    /**
     * 改变账单状态为已经支付
     *
     * @param bill
     */
    @Override
    public void changeState(Bill bill) {
        bill.setState(new HasPay());
    }
}
