//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Role.java
//  @ Date : 2019/9/5
//  @ Author : 
//
//




public abstract class Role {
	public void changeRole(Client client) {
	
	}
}
